apiVersion: apps/v1
kind: Deployment
metadata:
  name: pando-network-deployment
  labels:
    apptype: pando-network
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: pando-network
  template:
    metadata:
      labels:
        app: pando-network
        apptype: pando-network
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: pando-network
          image: gitdatateam/pando-network:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
