apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  pando-network
  annotations:
    meta.helm.sh/release-name: pando-network
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    apptype: pando-network
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release:  pando-network
spec:
  ingressClassName: {{.Values.ingress_name}}
  rules:
    - host: pando-network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pando-network-service
                port:
                  number: 80
