apiVersion: v1
kind: Service
metadata:
  name: pando-network-service
  labels:
    apptype: pando-network
spec:
  type: ClusterIP
  selector:
    app: pando-network
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80